name: qent
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.2.3
  flutter_bloc: ^8.1.5
  flutter_secure_storage: ^10.0.0
  get_it: ^9.2.0
  injectable: ^2.4.1
  equatable: ^2.0.8
  dio: ^5.9.0

dev_dependencies:
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
flutter_assets:
  assets_path: assets/
  output_path: lib/generated/
  filename: assets.dart
  ignore_comments: true
